import mongoose from "mongoose";

const orderModel = new mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        phoneNum:{
            type:String,
            required:true
        },
        PinCode:{
            type:String,
            required:true
        }
    },
    user:{
        type:mongoose.Schema.ObjectId,
        required:true,
        ref:"User"
    },
    orderItems:[
        {
            name:{
                type:String,
                required:true
            },
            quantity:{
                type:Number,
                required:true
            },
            product:{
                type:mongoose.Schema.ObjectId,
                required:true,
                ref:"Product"
            },
            price:{
                type:Number,
                required:true
            },
            image:{
                type:String,
                required:true,
                default:""
            }
        }
    ],
    itemsPrice:
    {
        type:String,
        required:true,
        default:0.0
    },
    taxPrice:{
        type:String,
        required:true,
        default:0.0
    },
    shippingPrice:{
        type:String,
        required:true,
        default:0.0
    },
    totalPrice:{
        type:String,
        required:true,
        default:0.0
    },
    payment:[
        {
            id:{
                type:String,
                required:true
            },
            status:{
                type:String,
                required:true
            }
        }
    ],
    paidAt:{
        type:Date
    },
    deliveredAt:{
        type:Date
    },
    orderStatus:{
        type:String,
        required:true,
        default:"processing"
    },
    createdAt:{
        type:Date,
        default:Date.now()
    }
})

const Order = new mongoose.model("Order",orderModel);

export default Order